version: "3.9"
    
services:
  db:
    image: mysql:5.7
    container_name: portfolio-site
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: wp.env
    
  wordpress:
    # build:
    #   context: .
    depends_on:
      - db
    image: wordpress:latest
    container_name: portfolio-site-mysql
    volumes:
      - ./themes:/var/www/html/wp-content/themes # {ホスト側の相対パス}:{コンテナ側の絶対パス}
      - ./html:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: wp.env
      
volumes:
  db_data: {}
  wordpress_data: {}

# 環境構築メモ:https://tech.recruit-mp.co.jp/infrastructure/post-11266/
