version: '3.7'
services:
  oracle:
    container_name: oracle-db
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"  # SQLNet
      - "5500:5500"  # EM Express
    environment:
      - ORACLE_PWD=oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/oracle123@//localhost:1521/XE as sysdba", "SELECT 1 FROM DUAL"]
      interval: 30s
      timeout: 10s
      retries: 5

  java-app:
    container_name: java-oracle-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
    depends_on:
      - oracle
    tty: true

volumes:
  oracle-data:
